// Script to deploy CYGAAR distributor contract on Abstract Testnet
// and initialize it with the existing CYGAAR token

const { ethers } = require("ethers");
const fs = require("fs");
const path = require("path");

// Load environment variables (create a .env file with these variables)
require("dotenv").config();

// Configuration
const config = {
  rpcUrl: "https://api.testnet.abs.xyz", // Abstract testnet RPC
  privateKey: process.env.PRIVATE_KEY, // Your deployer wallet private key
  penguinGameAddress: "0xB945d267eab7EfAe0b41253F50D690DBe712702C", // Existing game contract
  cygaarTokenAddress: "0x35EfA4699EdD7b468CBBf4FfF7B6e7AFC0A7aDa6", // Existing CYGAAR token
};

// Contract addresses will be populated during deployment
const addresses = {
  distributor: null,
};

// Function to compile distributor contract using Solc
async function compileContract() {
  console.log("Compiling distributor contract...");

  const solc = require("solc");

  // Read contract source
  const distributorSource = fs.readFileSync(
    path.resolve(__dirname, "../CygaarDistributor.sol"),
    "utf8"
  );

  // Prepare input for solc compiler
  const input = {
    language: "Solidity",
    sources: {
      "CygaarDistributor.sol": { content: distributorSource },
    },
    settings: {
      outputSelection: {
        "*": {
          "*": ["abi", "evm.bytecode"],
        },
      },
    },
  };

  // Compile contract
  const output = JSON.parse(solc.compile(JSON.stringify(input)));

  return {
    distributorAbi:
      output.contracts["CygaarDistributor.sol"].CygaarDistributor.abi,
    distributorBytecode:
      output.contracts["CygaarDistributor.sol"].CygaarDistributor.evm.bytecode
        .object,
  };
}

// Function to deploy distributor contract
async function deployDistributor(distributorAbi, distributorBytecode) {
  console.log("Deploying distributor contract...");

  // Connect to provider and create wallet
  const provider = new ethers.providers.JsonRpcProvider(config.rpcUrl);
  const wallet = new ethers.Wallet(config.privateKey, provider);

  // Get wallet info
  const balance = await wallet.getBalance();
  console.log(`Deploying from address: ${wallet.address}`);
  console.log(`Account balance: ${ethers.utils.formatEther(balance)} ETH`);

  // Deploy distributor contract
  console.log("\n1. Deploying CYGAAR Distributor contract...");
  const distributorFactory = new ethers.ContractFactory(
    distributorAbi,
    distributorBytecode,
    wallet
  );
  const distributorContract = await distributorFactory.deploy();
  await distributorContract.deployed();

  console.log(`CYGAAR Distributor deployed to: ${distributorContract.address}`);
  addresses.distributor = distributorContract.address;

  return distributorContract;
}

// Function to initialize distributor contract
async function initializeDistributor(distributorContract) {
  console.log("\n2. Initializing Distributor contract...");

  // Initialize distributor contract with token and game addresses
  const initTx = await distributorContract.initialize(
    config.cygaarTokenAddress,
    config.penguinGameAddress
  );
  await initTx.wait();

  console.log("Distributor initialized with:");
  console.log(`- Token contract: ${config.cygaarTokenAddress}`);
  console.log(`- Game contract: ${config.penguinGameAddress}`);

  // Activate distribution
  console.log("\n3. Activating distribution...");
  const activateTx = await distributorContract.setDistributionActive(true);
  await activateTx.wait();

  console.log("Distribution activated");
}

// Function to check contract state
async function verifyContractState(distributorContract) {
  console.log("\n4. Verifying contract state...");

  // Check if distribution is active
  const isActive = await distributorContract.distributionActive();
  console.log(`Distribution active: ${isActive}`);

  // Check penguin game contract
  const gameAddress = await distributorContract.penguinGame();
  console.log(`Game contract: ${gameAddress}`);

  // Check token contract
  const tokenAddress = await distributorContract.cygaarToken();
  console.log(`Token contract: ${tokenAddress}`);
}

// Save deployment info to file
function saveDeploymentInfo() {
  console.log("\n5. Saving deployment info...");

  const deploymentInfo = {
    network: config.rpcUrl,
    addresses: addresses,
    timestamp: new Date().toISOString(),
  };

  fs.writeFileSync(
    path.resolve(__dirname, "../deployment-info.json"),
    JSON.stringify(deploymentInfo, null, 2)
  );

  console.log("Deployment info saved to deployment-info.json");
}

// Generate frontend config
function generateFrontendConfig() {
  console.log("\n6. Generating frontend config...");

  // Create a config file for the frontend
  const frontendConfig = `// Auto-generated by deployment script
// Last updated: ${new Date().toISOString()}

export const CYGAAR_ADDRESSES = {
  TOKEN_ADDRESS: "${config.cygaarTokenAddress}",
  DISTRIBUTOR_ADDRESS: "${addresses.distributor}",
  PENGUIN_GAME_ADDRESS: "${config.penguinGameAddress}",
};
`;

  fs.writeFileSync(
    path.resolve(__dirname, "../../src/lib/tokenConfig.ts"),
    frontendConfig
  );

  console.log("Frontend config generated at src/lib/tokenConfig.ts");
}

// Main function
async function main() {
  try {
    console.log("=== CYGAAR DISTRIBUTOR DEPLOYMENT ON ABSTRACT TESTNET ===\n");

    // Validate that private key is provided
    if (!config.privateKey) {
      throw new Error(
        "Private key is required. Set the PRIVATE_KEY environment variable."
      );
    }

    // Compile contract
    const { distributorAbi, distributorBytecode } = await compileContract();

    // Deploy distributor
    const distributorContract = await deployDistributor(
      distributorAbi,
      distributorBytecode
    );

    // Initialize distributor
    await initializeDistributor(distributorContract);

    // Verify contract state
    await verifyContractState(distributorContract);

    // Save deployment info
    saveDeploymentInfo();

    // Generate frontend config
    generateFrontendConfig();

    console.log("\n=== DEPLOYMENT SUMMARY ===");
    console.log(`CYGAAR Token: ${config.cygaarTokenAddress}`);
    console.log(`CYGAAR Distributor: ${addresses.distributor}`);
    console.log(`Penguin Game: ${config.penguinGameAddress}`);
    console.log("\nNext steps:");
    console.log("1. Verify contracts on the Abstract testnet explorer");
    console.log("2. Test token claiming with a few addresses");
    console.log("3. Update the frontend with the new distributor address");
  } catch (error) {
    console.error("Error during deployment:", error);
    process.exit(1);
  }
}

// Run the script
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("Unhandled error:", error);
    process.exit(1);
  });
